### Get all products
GET http://localhost:8080/products

### Get five products
GET http://localhost:8080/products?limit=5

### Get product with id 2
GET http://localhost:8080/products/2

### Get product that not exits
GET http://localhost:8080/products/34123123