### Get all products
GET http://localhost:8080/products

### Get five products
GET http://localhost:8080/products?limit=5

### Get product with id 2
GET http://localhost:8080/products/2

### Get product that not exits
GET http://localhost:8080/products/34123123

### Create a product
POST http://localhost:8080/products
Content-Type: application/json

{
    "code": "2123",
    "title": "titulo",
    "description": "",
    "thumbnail": "nada",
    "price": 10,
    "stock": 0
}

### Create a product
PUT  http://localhost:8080/products
Content-Type: application/json

{
    "id": 2,
    "code": "2123",
    "title": "mi nuevo titulo",
    "description": "ahora tiene una descripcion",
    "thumbnail": "nada",
    "price": 10,
    "stock": 0
}